### ISSUE TITLE
Error with create-react-app

### ISSUE THREAD

**Issue by robcaldecott** [TeamWertarbyte/material-ui-bottom-sheet#1]
When using this with create-react-app I get a webpack error because the lib\bottomSheet.js file does not match the require in index.js:

Failed to compile.

```
Error in ./~/material-ui-bottom-sheet/lib/index.js
Module not found: [CaseSensitivePathsPlugin] `C:\Users\<me>\Projects\bottomsheet\node_modules\material-ui-bottom-sheet\lib\BottomSheet.js` does not match the corresponding path on disk `bottomSheet.js`.

 @ ./~/material-ui-bottom-sheet/lib/index.js 7:19-43
```

Looks like a simple build issue.

**Comment by saschb2b** [comment]
Seems to me like a create-react-app issue https://github.com/facebookincubator/create-react-app/issues/660
We're using this component in production. So the build should be good.

**Comment by robcaldecott** [comment]
If I npm intall on Windows then I end up with a file called `lib\bottomSheet.js` and your `index.js` is requiring `BottomSheet.js`. Note the case difference which causes the Webpack error. If I rename the file on disk to `BottomSheet.js` then it works. So I don't think this is a CRA issue, looks like this is the case used when you last npm published.

**Comment by leMaik** [comment]
@saschb2b I could reproduce this on Linux. The package seems to be broken.
![image](https://cloud.githubusercontent.com/assets/5544859/24104229/f99bde46-0d81-11e7-8385-532a2848f25e.png)

**Comment by saschb2b** [comment]
@robcaldecott @leMaik correct. I'll look into that. Thanks

**Comment by saschb2b** [comment]
@robcaldecott I just redeployed. Seems to have fixed the naming issue.

**Comment by vkpraveen** [comment]
I am getting below error.

Error in ./~/material-ui-bottom-sheet/lib/ExpandableBottomSheet.js
Module not found: 'react-custom-scrollbars' in C:\Users\mekak\Desktop\MobileApp\6101\inventorymobileui\node_modules\material-ui-bottom-sheet\lib
