### ISSUE TITLE
Bottom sheet with Material UI v1

### ISSUE THREAD

**Issue by akiroso** [TeamWertarbyte/material-ui-bottom-sheet#11]
Hey there, 

are there any plans on making bottom sheet compatible with material-ui v1?

**Comment by saschb2b** [comment]
@akiroso Yes, we are! We are trying to port all our components https://mui.wertarbyte.com/ from 0.1 to 1.0. You can see pre release ready 1.0 components on https://next.mui.wertarbyte.com/

**Comment by leMaik** [comment]
@akiroso Over at material-ui, we have implemented a swipeable drawer that can be anchored to the bottom of the screen. You can use that to implement a bottom sheet. In the future, a bottom sheet could land in material-ui itself or we might port it here. :+1:

**Comment by dcworldwide** [comment]
Just want to know if this project is still required to create a bottom sheet with the latest mui?

**Comment by leMaik** [comment]
@dcworldwide in 1.0 or later, you can use the swipeable drawer with anchor="bottom" to get a bottom sheet. 🙃 

I'll close this issue.

**Comment by dcworldwide** [comment]
Sweet. Thanks
