### ISSUE TITLE
Module not found: 'react-custom-scrollbars' in 

### ISSUE THREAD

**Issue by vkpraveen** [TeamWertarbyte/material-ui-bottom-sheet#2]
I am getting below error.

Error in ./~/material-ui-bottom-sheet/lib/ExpandableBottomSheet.js
Module not found: 'react-custom-scrollbars' in C:\Users\xxxxx\Desktop\MobileApp\node_modules\material-ui-bottom-sheet\lib

But when I added npm install react-custom-scrollbars --save -dev it's wokring fine.

I think dependancies should come part of the installation of this library instead of adding manually.

**Comment by saschb2b** [comment]
Thought I added it as peerDependencies. I'll check that

**Comment by leMaik** [comment]
Since npm@3, peer dependencies are not installed automatically.

@vkpraveen It's intentionally added as a peer dependency because it can be shared across different libraries and you should probably add it with `--save` instead of `--save-dev`.

Edit: We should add a note to the docs, though.
