### ISSUE TITLE
Gray-background overlay allowing click-through on Android 

### ISSUE THREAD

**Issue by tonymckendry** [TeamWertarbyte/material-ui-bottom-sheet#8]
For some reason, when I click the gray background to dismiss it when running on Android (via Cordova), I am able to click through to other components under the background which is causing some unwanted behavior. So far, I haven't been able to replicate this behavior any other way.

**Comment by saschb2b** [comment]
@tonymckendry I can reproduce this on our site https://lift.fail/ as well. But only using touch events. Click events work as expected. Will see why this is bubbling up when touching.

**Comment by tonymckendry** [comment]
Thanks a lot! Glad it wasn't just me :)

**Comment by jaskinn** [comment]
Is there any progress with this?

**Comment by leMaik** [comment]
Just found a solution, give me a ~minute~ day. :smile:
